name: Build ExpressLRS
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO
      run: |
        platformio platform update
        mkdir -p ~/artifcats
        cd src
        export PLATFORMIO_BUILD_FLAGS=-DRegulatory_Domain_AU_433
        platformio run
        mv .pio/build ~/artifcats/AU_433
        export PLATFORMIO_BUILD_FLAGS=-DRegulatory_Domain_AU_915
        platformio run
        mv .pio/build ~/artifcats/AU_915
        export PLATFORMIO_BUILD_FLAGS=-DRegulatory_Domain_EU_868
        platformio run
        mv .pio/build ~/artifcats/EU_868
        export PLATFORMIO_BUILD_FLAGS=-DRegulatory_Domain_EU_433
        platformio run
        mv .pio/build ~/artifcats/EU_433
    - name: Upload artifcats
      uses: actions/upload-artifact@v2-preview
      with:
        name: firmware
        path: ~/artifcats/**/*.bin
